### ISSUE TITLE
Issue while running

### ISSUE THREAD

**Issue by Tlazypanda** [Mishalfatima/Inter-Video-Frame-Forgery-Detection#1]
I am trying to setup this project on my system for educational purposes but am having some issues with running it.

![image](https://user-images.githubusercontent.com/33183263/80227787-ca303100-866b-11ea-8020-ff5ed48bf79a.png)

I have modified the code in read_data.py file so that the traceback is easier to understand and debug -
```
62 print(self.im_ind)
124 print(video)
```
Complete Traceback:

```
Device being used: cpu
10
Training C3D from scratch...
Total params: 78.00M
Training model on dashcam dataset...
['/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000057.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000263.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000399.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000129.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000088.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000098.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000400.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000217.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000068.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000285.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000257.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000336.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000376.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000086.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000057.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000263.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000399.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000129.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000088.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000098.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000400.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000217.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000068.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000285.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000257.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000336.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000376.mp4', '/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000086.mp4']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
/home/snehamishra/anaconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:122: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
c28
0
/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/Anticipating-Accidents-master/dataset/videos/training/frames_train/000086.mp4
Traceback (most recent call last):
  File "main.py", line 269, in <module>
    main()
  File "main.py", line 262, in main
    train_C3D(args)
  File "main.py", line 98, in train_C3D
    inputs, labels = dataset.get_next_batch(args.batch_size,args.clip_len)
  File "/home/snehamishra/Documents/Inter-Video-Frame-Forgery-Detection-master/read_data.py", line 127, in get_next_batch
    path, dirs, files = next(os.walk(video))
StopIteration
```
Can you kindly help me with running this please?

**Comment by Tlazypanda** [comment]
@Mishalfatima can you kindly help me? Thanks :smile:

**Comment by Mishalfatima** [comment]
Hi!
The video that is passed in the os.walk function should be the folder that consists all the frames of the video, not the .mp4 file. Hope it helps.

**Comment by Tlazypanda** [comment]
@Mishalfatima Thanks a lot !! :100:
